### ISSUE TITLE
Hello from CCCS! 🍁

### ISSUE THREAD

**Issue by cccs-rs** [RussianPanda95/Configuration_extractors#2]
Hi there,

I was wondering if you're interested in including your extractors in [Assemblyline](https://cybercentrecanada.github.io/assemblyline4_docs/), our open-source malware analysis platform.

I believe adding the work that you've done would be a boon to the cybersecurity community!

If you're interested or having any questions, feel free to reach out! 😀

**Comment by RussianPanda95** [comment]
> 



> Hi there,
> 
> I was wondering if you're interested in including your extractors in [Assemblyline](https://cybercentrecanada.github.io/assemblyline4_docs/), our open-source malware analysis platform.
> 
> I believe adding the work that you've done would be a boon to the cybersecurity community!
> 
> If you're interested or having any questions, feel free to reach out! 😀

Hi! Thank you for reaching out :)

It would be great if you could include my configuration extractors in your malware analysis platform. You can also find other configuration extractors in my company's repository https://github.com/esThreatIntelligence/RussianPanda_tools

Please let me know if you have any questions

Thank you!

**Comment by cccs-rs** [comment]
Thanks for the response!

As a question: do you, or your company, have an output standard for your extractors?
If not, would you consider a shift to something like [MACO](https://github.com/CybercentreCanada/maco) where you could port your extractors to follow that framework?

We have a [library](https://github.com/CybercentreCanada/configextractor-py) that we run within Assemblyline that can run extractors under known frameworks (MWCP & MACO currently supported, working on malduck and CAPE!) and aggregate their output for tagging/scoring (which is why some kind of deterministic output is required). 

This library can be used outside of the Assemblyline context too 😉 so maybe it could be handy for you and your company?

**Comment by cccs-rs** [comment]
??

**Comment by RussianPanda95** [comment]
Hi there!

Apologies for the delayed response. I recently started a new job, and we’re currently exploring the integration of Assemblyline. I could use some assistance with getting familiar with MACO 😄

**Comment by cccs-rs** [comment]
Hello again! 🤓

No worries! I'd be happy to assist with anything MACO or Assemblyline related.

You can join our Discord community to reach us more directly for more support/discussion: https://discord.gg/GUAy9wErNu
